Currently blows up, but for the record
Causes xml2rfc to blow up:
  <seriesInfo name='Proceedings of the International School of Physics &ldquo;Enrico Fermi&rdquo;' value='vol. 162, pp. 115–218'/>

rdviii@Rods-Air draft-van-meter-qirg-quantum-network-architecture % xml2rfc draft-van-meter-qirg-quantum-network-architecture.xml
Error: Unable to parse the XML document: draft-van-meter-qirg-quantum-network-architecture.xml
 /Users/rdviii/Documents/GitHub/draft-van-meter-qirg-quantum-network-architecture/draft-van-meter-qirg-quantum-network-architecture.xml: Line 1752: Entity 'ldquo' not defined
 /Users/rdviii/Documents/GitHub/draft-van-meter-qirg-quantum-network-architecture/draft-van-meter-qirg-quantum-network-architecture.xml: Line 1752: Entity 'rdquo' not defined

Due to
  hein-multiparty: DOI.10.1103/PhysRevA.69.062311